### ISSUE TITLE
Projeyi çalıştırırken problem yaşıyorum

### ISSUE THREAD

**Issue by SalihCanBinboga** [fevziomurtekin/hackernewsapp#5]
İlgili hatanın görüntüsü -> [https://i.hizliresim.com/pPDspR.jpg](url)

Bir türlü gideremedim yardımcı olursanız sevinirim

**Comment by fevziomurtekin** [comment]
Layoutlar da items ve activities de dizinlerindeki main altdizinleri çakışıyor. Yeni bir güncelleme attım uygulamaya. Uygualamayı pull edip tekrardan denersen düzelecektir diye tahmin ediyorum.

**Comment by SalihCanBinboga** [comment]
Anladım pull ardından bu hatayı almaya basladım https://i.hizliresim.com/afD9Pc.jpg @fevziomurtekin
